### ISSUE TITLE
Custom List Editor - Initial UI design

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/circulation-web#112]
The admin interface needs a mechanism for creating and editing custom lists. This issue tracks the UI work, which is the first part of the work.

First pass wireframes: https://docs.google.com/presentation/d/1j3Wspa-QIGJm-VWE67-zgPQAgeJ3r408UgHwu3gauY8/edit#slide=id.g25176a4218_0_19

**Comment by ricardoom** [comment]
this is _Large_ task

**Comment by ricardoom** [comment]
https://github.com/ricardoom/SE-Admin-UI

**Comment by leonardr** [comment]
Can we mark this as done?

**Comment by ricardoom** [comment]
yes

Ricardo E. Galvez
Designer
