### ISSUE TITLE
Link to book detail pages from list view

### ISSUE THREAD

**Issue by aslagle** [NYPL-Simplified/circulation-web#120]
If there are multiple books with the same title or an incorrect title, the admin needs to be able to get to the book detail page for a specific book in the list.

Also, add some padding below the "Load more" button.

**Comment by jce1028** [comment]
Specifically, this is so librarians can correct metadata as the refine their display of books they want to present or highlight in specific list.  another option is to ad any other info like subtitle and series info along with the title in the search result list so as to better differentiate books in the same meta series.
