### ISSUE TITLE
error thrown when clicking on complaints feed from edit tab

### ISSUE THREAD

**Issue by skomputer** [NYPL-Simplified/circulation-web#35]
As far as we can tell this only occurs in an incognito browser.

**Comment by aslagle** [comment]
This was introduced in the resolve complaints branch, doesn't happen on master yet.

**Comment by skomputer** [comment]
It only occurs for books with complaints, and is caused by a bug in OPDS Browser, which sometimes renders BookDetailsContainer without a bookUrl.

**Comment by skomputer** [comment]
Fixed in OPDS Browser: https://github.com/NYPL-Simplified/opds-browser/pull/123.
